### ISSUE TITLE
Dynamic Requires

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-utils#29]
@jdfreder @jasongrout @sccolbert @minrk 

I am in favor of the following: 
1) For now, assume RequireJS is a global (script tag or `global.requirejs = require('requirejs');`).  It has already caused problems as an import.
2) When WebPack 2.0 is released, use `System.import('dynamic/' + moduleName)`.

Then, we can specify that `dynamic/*` uses an external loader in WebPack, and add a `dynamic/` handler to the server.  I believe this gives us the best interoperability with all loaders and environments.

**Comment by blink1073** [comment]
cc @SylvainCorlay 

Actually, no new server component would be needed if we configure `System` to strip the `dynamic/`

**Comment by blink1073** [comment]
Updated idea: move `loadClass` to `jupyter-js-domutils`, and use the `require([..], function` syntax: https://webpack.github.io/docs/code-splitting.html#amd-require, to be replaced by `System.import` in Webpack 2.0.

**Comment by blink1073** [comment]
Argh, we cannot do that, since we need `loadClass` in `jupyter-js-services`.

**Comment by blink1073** [comment]
We could support Webpack and node with the following shim (Browserify would no longer work, but we have already decided Browserify is a non-starter due to its handling of CSS.

```
if(typeof require.ensure === "undefined")
  require.ensure = require('node-ensure'); // shim for node.js
}
require.ensure(...)
```

**Comment by jdfreder** [comment]
@blink1073 I'm happy with 1 and think I'm happy with 2, although I haven't used SystemJS yet.

**Comment by minrk** [comment]
ditto @jdfreder

**Comment by blink1073** [comment]
It appears that the way to handle this is to use `window.require` or `window.SystemJS` (with node shims for `global`).  Webpack ignores these calls.

cc @SylvainCorlay
