### ISSUE TITLE
Fix getWsUrl

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-utils#35]
Should only slice the baseUrl if it starts with http.

**Comment by blink1073** [comment]
@ellisonbg, @minrk I'm trying to determine the right way to handle `wsUrl` on https://demohub.jupyter.org/user/blink1073/lab.  I'm getting `"/user/blink1073/"` for the `baseUrl`, and `location.origin` is `"https://demohub.jupyter.org"`, I'm assuming the `wsUrl` should be `wss://demohub.jupyter.org/user/blink1073`, and we should change `getWsUrl` as follows:

``` diff
diff --git a/src/index.ts b/src/index.ts
index 602973c..e102ced 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -449,6 +449,13 @@ function getWsUrl(baseUrl?: string): string {
   let wsUrl = getConfigOption('wsUrl');
   if (!wsUrl) {
     baseUrl = baseUrl || getBaseUrl();
+    if (baseUrl.indexOf('http') !== 0) {
+      if (typeof location === 'undefined') {
+        baseUrl = urlPathJoin(location.origin, baseUrl);
+      } else {
+        baseUrl = urlPathJoin('http://localhost:8888/', baseUrl);
+      }
+    }
     wsUrl = 'ws' + baseUrl.slice(4);
   }
   return wsUrl;
```

**Comment by minrk** [comment]
@blink1073 that sounds exactly right, thanks!
